### ISSUE TITLE
nextcloud-desktop-client snap doesn't work with ubuntu 20.4

### ISSUE THREAD

**Issue by jsobiecki** [glasen/snap-nextcloud-desktop-client#1]
Hello,

I installed snap using following command:
`sudo snap install --classic nextcloud-desktop-client`

After that, I was able to authenticate against our nextcloud server. Unfortunately, later sychrnosiation doesn't work. In app, I'm getting
"Could not read system exclude file:.

I checked system logs, and this entry seems like a direct reason of problem: 

`sty 07 11:49:33 pecet audit[36819]: AVC apparmor="DENIED" operation="open" profile="snap.nextcloud-desktop-client.nextcloud" name="/etc/Nextcloud/sync-exclude.lst" pid=36819 comm="nextcloud" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0`

**Comment by jsobiecki** [comment]
I found apparmor profile (`snap.nextcloud-desktop-client.nextcloud`) and I added following entry to it:

`
  # Added sync-exclude 
  /etc/Nextcloud/sync-exclude.lst r,
`

This fixed problem for me.

**Comment by glasen** [comment]
Strange thing. Did you create the mentioned file own your own?

**Comment by monochromec** [comment]
Unfortunately jsobieckie's approach didn't fix the problem for me. Even setting the apparmor profile mode to "complain" instead of "enforce" (which is the default) still caused apparmor to deny access to the file.

**Comment by glasen** [comment]
I will try to include the directory and file by using the "system-files"-interface in the snap. I will upload a test version of the snap on Thursday or Friday to the edge-channel.

**Comment by glasen** [comment]
I've created a snap package with the system-files-plug mentioned above:

https://drive.google.com/file/d/11bCLP3jfwOS3it4b0rbVXYrw0zBy2MCX/view?usp=sharing

Could you please try it? To install the package and enable the interface you have to use the following commands:
```
sudo snap install --dangerous nextcloud-desktop-client_3.4.1_multi.snap
sudo snap connect nextcloud-desktop-client:etc-nextcloud
```
