### ISSUE TITLE
Recurring popup error related to logging problem

### ISSUE THREAD

**Issue by kylespencer** [glasen/snap-nextcloud-desktop-client#10]
#### Describe the bug
The new 3.5.3 snap client is constantly throwing error dialog boxes that complain about an inability to write to a log file. Specifically, the dialog says:

File "/home/user/snap/nextcloud-desktop-client/82/.config/Nextcloud//logs/20220926_0737_owncloud.log.0"
cannot be opened for writing. The log output cannot be saved!

#### To Reproduce
1. Upgrade to the latest snap version
2. Sync some files
3. Experience popups

#### Expected behavior
No popup errors.

#### OS/snapd/snap version
Ubuntu 22.04
nextcloud-desktop-client 3.5.3 93 latest/stable glasen

**Comment by kylespencer** [comment]
The issue may be related to the double dash (//) in the path.

**Comment by glasen** [comment]
Are you sure you are using the latest version? A few revisions ago, i've added a patch which moves to log-directory to "/home/user/snap/nextcloud-desktop-client/current/common".

Did you ever restart your PC or at least the client? This error only occurs when you're upgrading the client without restarting it.

**Comment by kylespencer** [comment]
Restarting the client seems to have resolved the issue. Thank you!
